#!/bin/bash

## This script is designed to minimize frustration when adding new service groups to a VCS cluster in online mode.
## Assumes all nodes go into autostart and system list

## Revision History
## Version 0.5 - 14 July 	2014 - Barret Spangler - Fixed node/counter mismatch
## Version 0.4 - 17 January 2014 - Barret Spangler - Run through testing on live SFHA 6.1 system. Fixed some minor flow problems.
## Version 0.3 - 10 January 2014 - Barret Spangler - Finished service group type selector, refines functions. Reformatted for clarity. 
## Version 0.2 - 08 January 2014 - Barret Spangler - added some extra functionality. not quite functional in this state
## Version 0.1 - 07 January 2014 - Barret Spangler - Base Version
##########################################################################################################################################
## Test for runtime options

# We need two runtime variables, sgname and sgtype. Check to make sure that two values are there
expected_args=2
if [ $# -ne $expected_args ]; then
        echo -e "Usage: `basename $0` <service group name> <Parallel|Failover>"
        exit 1
fi

# Variable 2 needs to be either "Parallel" or "Failover" - no other options are valid.
if [ $2 != "Parallel" -a $2 != "Failover" ]
        then
                echo "Service Group Type not valid"
                echo -e "Usage: `basename $0` <service group name> <Parallel|Failover>"
                exit 1
fi


## Now assign human-friendly variable names
sgname="$1"
sgtype="$2"
hagroup=/opt/VRTS/bin/hagrp
hasystem=/opt/VRTS/bin/hasys
hastat=/opt/VRTS/bin/hastatus

## some functions for later on
# build system and autostart list

autostart(){
autostartlist=""
for i in $($hasystem -state | grep -v "#System" | awk '{print $1}')
        do autostartlist=`echo $autostartlist $i`
done
}

syslist(){
systemlist=""
node=0
for i in $($hasystem -state | grep -v "#System" | awk '{print $1}')
        do systemlist=`echo $systemlist $i $node`
        node=$((node + 1))
done
}

# build the failover group
failover(){
        $hagroup -add $sgname &>/dev/null
        $hagroup -modify $sgname SystemList $systemlist
        $hagroup -modify $sgname AutoStartList $autostartlist
        $hagroup -modify $sgname Enabled 1
		$hastat -sum
		echo $sgname "successfully built"
        exit 0
}

# build the parallel group
parallel(){
        $hagroup -add $sgname &>/dev/null
        $hagroup -modify $sgname SystemList $systemlist
        $hagroup -modify $sgname AutoStartList $autostartlist
        $hagroup -modify $sgname Parallel 1
        $hagroup -modify $sgname Enabled 1
		$hastat -sum
		echo $sgname "successfully built"
        exit 0
}

##########################################################################################################################################
autostart
syslist
/opt/VRTS/bin/haconf -makerw &>/dev/null
case "$sgtype" in
        "Failover")
                failover
        ;;
        "Parallel")
                parallel
        ;;
esac

# If the script makes it this far, something's gone wrong.
echo "Service group not completely build. Run 'hagrp -display <service group name>' to see if it was built"
exit 1